### ISSUE TITLE
Exception thrown with Robmikh.CompositionSurfaceFactory 0.6.0-alpha

### ISSUE THREAD

**Issue by darenm** [robmikh/compositionimageloader#15]
Hey just trying out the factory. I get an exception thrown with this code:

``` csharp
            var surfaceFactory = SurfaceFactory.CreateFromCompositor(_compositor);
```

I am running this version of Windows 10:
![image](https://cloud.githubusercontent.com/assets/1674843/19001754/07aea2a0-8706-11e6-8b11-b52853bdddda.png)

Exception details:

```
System.TypeLoadException occurred
  HResult=0x80131522
  Message=Requested Windows Runtime type 'Robmikh.CompositionSurfaceFactory.SurfaceFactory' is not registered.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at System.StubHelpers.StubHelpers.GetWinRTFactoryObject(IntPtr pCPCMD)
   at Robmikh.CompositionSurfaceFactory.SurfaceFactory.CreateFromCompositor(Compositor compositor)
   at AlphaMaskDemo.MainPage.<MainPage_Loaded>d__3.MoveNext() in C:\Users\Daren\Documents\Visual Studio 15\Projects\AlphaMaskDemo\AlphaMaskDemo\MainPage.xaml.cs:line 89
Inner Exception 1:
COMException: Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG))
```

**Comment by robmikh** [comment]
That's strange, I'm unable to reproduce this issue. Usually a type load exception means that either a dependency is missing or the namespace is screwed up. It shouldn't be the namespace issue, as I just spun up a new project and included the Nuget package and was able to create a `SurfaceFactory` and create a surface.

What version of Windows is your project targeting (both min and target)? What configuration are you targeting (ARM, x86, x64)?

**Comment by darenm** [comment]
![image](https://cloud.githubusercontent.com/assets/1674843/19005238/b1f2a350-8716-11e6-9111-65af85061a95.png)

x86 target on x64 machine - I'll try x64.

**Comment by darenm** [comment]
That was it - runs fine targeting x64 .

**Comment by robmikh** [comment]
Hmmmm... well that should be enough to get you unblocked, but I'm still worried about x86. I tried both x86 and x64 in my test. All three configurations are supported, but it is possible I've screwed something up in the packaging.

The next time you run into this, could you try flushing the nuget cache and doing a clean build?

**Comment by darenm** [comment]
Sure - the new NuGet is particularly fun that way... this was the first time I had installed and used the SurfaceFactory vs. the SurfaceLoader.
