### ISSUE TITLE
ARM64 Support

### ISSUE THREAD

**Issue by azchohfi** [robmikh/compositionimageloader#26]
ARM64 support would be nice. We have a dependency on this package on the Windows Community Toolkit (https://github.com/windows-toolkit/WindowsCommunityToolkit).

**Comment by robmikh** [comment]
We'll need Win2D to publish ARM64 support first, which seems to be tracked by https://github.com/microsoft/Win2D/issues/637.

Aside from that, I'll need to look into getting some ARM64 hardware so I can actually make sure I'm adding the platform correctly in VS. I've been meaning to pick one up for awhile now to play with, so I'm glad I have an excuse now 😄 .

Please let me know if you have any recommendations on hardware or adding ARM64 as a platform in VS.

**Comment by MagicAndre1981** [comment]
> Aside from that, I'll need to look into getting some ARM64 hardware so I can actually make sure I'm adding the platform correctly in VS. 

if you have a Lumia 950(XL), install the [ARM64 Windows 10 1903](https://github.com/WOA-Project/WOA-Deployer-Lumia) on it side by side to Win10 Mobile.

**Comment by robmikh** [comment]
I ended up picking up a Lenovo Yoga C630, but I might give that a try on my 950XL for shits and giggles. Thanks!

**Comment by robmikh** [comment]
Fixed with 7f4c610f9085af0d88d844ff74cf777a6dcf634a and part of release [v0.8.3](https://github.com/robmikh/compositionsurfacefactory/releases/tag/v0.8.3).
