### ISSUE TITLE
Apparent loss of image quality

### ISSUE THREAD

**Issue by XamlBrewer** [robmikh/compositionimageloader#9]
There's a loss of image quality when using CompositionImageLoader compared to Microsoft.UI.Composition.Toolkit (https://github.com/Microsoft/WindowsUIDevLabs/tree/master/Demos/Reference%20Demos/Microsoft.UI.Composition.Toolkit).

Some images in some resolutions (it's not always significant) are displayed more grainy (loss of DPI?) and transparent pixels are displayed as white.

Screenshots are available in this blog post: https://xamlbrewer.wordpress.com/2016/07/11/building-a-uwp-rating-control-using-xaml-and-the-composition-api/

**Comment by robmikh** [comment]
So it looks like the lack of a decode size is the culprit. If you don't specify the desired decode size when using the Microsoft.UI.Composition.Toolkit version, then it looks the same as the ImageLoader version.

Unless I'm mistaken, I don't think [Win2D](https://github.com/Microsoft/Win2D/) provides a way to specify the desired decoded size of a `CanvasBitmap`. Looks like I'll have to make a pull request to Win2D to fix this (or ask them to add the feature).

Thanks for the heads up!

**Comment by robmikh** [comment]
It looks like the decoded size is actually just used to interpolate the image before it is put into a D2D/D3D texture. The interpolation method is WIC's Fant interpolation, which would explain the difference in quality.

I may be able to use a different interpolation method later on in the chain, from the D2D/D3D texture to the Composition surface, and achieve a similar effect. I _think_ that I'll have to utilize the `Transform` property on the `CanvasDrawingSession` to properly get the effects of the interpolation mode. Unfortunately, Fant isn't available so I'll have to play with `CanvasImageInterpolation::HighQualityCubic`.

**Comment by robmikh** [comment]
No longer blocked.

Just setting a different interpolation mode (I used `CanvasImageInterpolation::HighQualityCubic`) in the `DrawImage` call does the trick. Using a better interpolation mode I was able to get this working:

![win2dinterp](https://cloud.githubusercontent.com/assets/7089228/17162249/5967eece-5369-11e6-95e7-8aa501e8cc5d.png)

The left is with linear interpolation set (the default for Win2D) and the right has `HighQualityCubic` set.

**Comment by robmikh** [comment]
Incorporating this will require an API change, as I don't want to just force everyone to use a more expensive interpolation mode, especially when that might be overkill or the effect is undesired. Pixel art tends to look pretty horrible on anything BUT nearest neighbor.

This will probably end up going into the C++/CX version ([CompositionSurfaceFactory](https://github.com/robmikh/compositionimageloader/tree/dev)).

**Comment by robmikh** [comment]
Addressed with commit 8975ceafb23a39166f1ed01d7207368ba31fd679.

**Comment by robmikh** [comment]
This is resolved with the C++/CX rewrite, but I'm going to keep this open until I ship the new version.
